### PR TITLE
Fix: playing of instrument without note.

### PR DESCRIPTION
**Pull request by rasky**
When an instrument is played without a note, the current playing
sample should restart its envelope, keeping its position. So it's
important not to change the current instrument.

Also, the same behavior happens even if the instrument is invalid (and
no note is specified); on the other hand, if the instrument is invalid
and a note is specified, the current note is being cut.

Co-developed with @bryc, who also prepared the tests

### CODE REVIEW

**Comment by Artefact2** [comment]
Thanks for the fix, it has been merged into 657662eb0cce6b9c1461ccb06e1fd74373a63381.

I merged the three test cases into one module, where it's easy to compare what is and isn't working. The output from libxm is OK for ghost instruments with different/invalid instruments, but becomes wrong when ghost notes are played afterwards. I tested it against MilkyTracker only, and maybe it's wrong on that too.

**Comment by rasky** [comment]
Can you explain the logic of row 1C where you have `L18` in channel 2? How can that match a rekey in channel 1?

**Comment by Artefact2** [comment]
In channel 1, the envelope resets at row 18 and pitch changes at row 1C. To simulate that effect in channel 2 (without using ghosts) I trigger the instrument at the correct pitch, but at envelope position 24 (four rows are separated by 24=0x18 ticks). Sample position doesn't exactly match, but because the loop is so short it's not an audible difference.

**Comment by bryc** [comment]
Nice test case @Artefact2, this might be showing behavior that isn't highlighted in the initial tests I did. In case you don't know, OpenMPT also has some test cases that may or may not have this issue already: https://wiki.openmpt.org/Development:_Test_Cases/XM.

> I tested it against MilkyTracker only, and maybe it's wrong on that too.

Here is Milky compared to other replayers. It does seem to be wong. But it seems a lot of them do their own thing. FT2-clone would be the most accurate as it's based on the original FT2 source code.

Compare

**Pull request merged**
