### PR TITLE
Fix playing of undefined patterns

### PR DESCRIPTION
**Pull request by rasky**
Some XM modules contain a pattern table that references an undefined
pattern (whose index is higher than the number of patterns). Both
ft2-clone and MilkyTracker agree that those are empty patterns of 64
rows and play them accordingly.

This commit does the same in libxm, avoiding a segfault.

### CODE REVIEW

**Comment by rasky** [comment]
Example of such module, see last pattern
[polyamber.zip](https://github.com/Artefact2/libxm/files/7566843/polyamber.zip)

**Comment by Artefact2** [comment]
Thanks for the contribution. Are we using the same libxm base? Because it doesn't segfault on undefined patterns (see https://github.com/Artefact2/libxm/blob/340033a7b0d56ccec329bb2c1fccc264ad57fe44/src/load.c#L60).

Your fix is better than just discarding them, as it conforms to what trackers do, but as-is it does nothing on the current codebase. I also changed `xm_get_number_of_rows()` so that players can report more accurate position information. See 68bd967 and 94b5121.

**Comment by rasky** [comment]
I think that happens because I don't use XM_DEFENSIVE. 

Do we need a compile time macro for that BTW? The fixes I have provided over the months were all in the direction of sanitizing against weird modules, which I think it can be done efficiently without guarding them with a compile time macro.

**Comment by Artefact2** [comment]
The original idea was to save a few bytes in demos, where you know the module you're loading is OK. Either way the undefined pattern stuff is now there regardless of that compile-time flag.

**Pull request merged**
