### PR TITLE
Add xm_create_context_safe(), avoid buffer overruns

### LINKED ISSUE #6: Buffer overrun in xm_create_context
I'm writing a [Rust wrapper](https://github.com/nukep/libxm-rs) for `libxm`, and noticed that there's no bounds for `moddata` in `xm_create_context()`. This is obviously bad if `moddata` is corrupted or invalid.

From what it appears, you seem to be aware of this issue already; it's listed in the README as:
* Loading a bogus file (that yet has a valid 60-byte header) will probably result in a segmentation fault.

---
Are there any plans to address this issue in the near future?

### PR DESCRIPTION
**Pull request by nukep**
A safer `xm_create_context_safe()` function was added for creating the XM context; the now-deprecated `xm_create_context()` remains for backwards compatibility.

I originally attempted to error-handle all invalid reads, but that turned out extraordinarily verbose and difficult. :)
So I did what @Artefact2 suggested and padded out-of-bounds reads with 0.

All of the `READ_x` macros will now return 0 if the provided offset exceeds the bounds of `moddata`.
All occurrences of `memcpy` were also replaced with a new `READ_MEMCPY` macro that pads with zeros.

Fixes #6

### CODE REVIEW

**Comment by Artefact2** [comment]
Looking good. Don't forget to add your name/email before the license header where you made non-trivial changes, like [this](https://github.com/Artefact2/libxm/commit/f24bcab98f695ef201fd75adfc04b2ffc85faec9#diff-0f9b4e0baa3ae1916003522e1f2d8bb6R2).

**Comment by nukep** [comment]
GNU's rules are confusing. So, the version's supposed to be bumped to `1.0.0` because "an interface was added"? :confused:
I typically follow the [SemVer](http://semver.org/) rules as used in node.js (`major.minor.patch`), so it would become `0.1.0`. Intuitively, it's _probably_ the same rules as GNU's, though.

**Comment by Artefact2** [comment]
Should be 1:0:1. Old programs will work with the new library (no relinking needed) but new programs might not work with the old library.

**Comment by nukep** [comment]
Done.

**Comment by Artefact2** [comment]
Thanks!

**Pull request merged**
