### PR TITLE
Fix channel panning ramps.

### PR DESCRIPTION
**Pull request by rasky**
It looks like in FT2, panning is made using an exponential scale, based
on sqrt. This PR allows to match panning performed by MilkyTracker
and OpenMPT. 

MilkyTracker:
https://github.com/milkytracker/MilkyTracker/blob/be016986168a4d03b8d160303fa61296070a6e2c/src/milkyplay/ChannelMixer.cpp#L583

FT2-clone:
https://github.com/8bitbubsy/ft2-clone/blob/8af2e42736b61a36a0d54bede93a47a1bab35f5d/src/ft2_audio.c#L192

The attached test makes it easy to reproduce the issue.

Co-developed with @bryc who also prepared the test.

### CODE REVIEW

**Comment by bryc** [comment]
Discussion of a PR that went into MilkyTracker about FT2 panning: https://modarchive.org/forums/index.php?topic=3517.0

Here's an audio comparison. XMPlay by default has "FT2 panning" turned off, but turning it on fixes the result to match others.

ft2_panning_law

**Comment by Artefact2** [comment]
Thanks for fixing the panning formula, one more case of the spec being incomplete ;-) Makes sense to not use just a linear fade, because that's not how perceived loudness works at all.

Doing two calls to `sqrt()` per channel per sample might be a bit wasteful on resources (I am seeing a 10% performance penalty on a 32-channel module, and 30% penalty with the prod cflags). I will look into doing the calculation in `xm_tick()` only, near line 1198.

**Comment by rasky** [comment]
That doesn't work with ramping though, at least not with the current formula. I've tried doing ramping post-sqrt (actually, even post vol*pan calculation) and it seems to work just as well. Up to you

**Comment by Artefact2** [comment]
Merged in ad599b87e8f52243361b73bb878f4224bf3b674d. See 91a87591a7fbe3eeb256e8c2e56f2c8e33827ab7 for saving some runtime resources.

**Pull request merged**
